// GENERATED — country metadata for every entity in data/countries-50m.json.
// name -> [continent, iso2 ('' = no flag), sovereign 1/0, display name]
// Sovereign = UN members + observers (Vatican, Palestine) + Taiwan + Kosovo.
window.COUNTRY_META = {
  "Afghanistan": ["Asia", "af", 1, "Afghanistan"],
  "Albania": ["Europe", "al", 1, "Albania"],
  "Algeria": ["Africa", "dz", 1, "Algeria"],
  "American Samoa": ["Oceania", "as", 0, "American Samoa"],
  "Andorra": ["Europe", "ad", 1, "Andorra"],
  "Angola": ["Africa", "ao", 1, "Angola"],
  "Anguilla": ["North America", "ai", 0, "Anguilla"],
  "Antarctica": ["Antarctica", "aq", 0, "Antarctica"],
  "Antigua and Barb.": ["North America", "ag", 1, "Antigua and Barbuda"],
  "Argentina": ["South America", "ar", 1, "Argentina"],
  "Armenia": ["Asia", "am", 1, "Armenia"],
  "Aruba": ["North America", "aw", 0, "Aruba"],
  "Ashmore and Cartier Is.": ["Oceania", "", 0, "Ashmore and Cartier Islands"],
  "Australia": ["Oceania", "au", 1, "Australia"],
  "Austria": ["Europe", "at", 1, "Austria"],
  "Azerbaijan": ["Asia", "az", 1, "Azerbaijan"],
  "Bahamas": ["North America", "bs", 1, "Bahamas"],
  "Bahrain": ["Asia", "bh", 1, "Bahrain"],
  "Bangladesh": ["Asia", "bd", 1, "Bangladesh"],
  "Barbados": ["North America", "bb", 1, "Barbados"],
  "Belarus": ["Europe", "by", 1, "Belarus"],
  "Belgium": ["Europe", "be", 1, "Belgium"],
  "Belize": ["North America", "bz", 1, "Belize"],
  "Benin": ["Africa", "bj", 1, "Benin"],
  "Bermuda": ["North America", "bm", 0, "Bermuda"],
  "Bhutan": ["Asia", "bt", 1, "Bhutan"],
  "Bolivia": ["South America", "bo", 1, "Bolivia"],
  "Bosnia and Herz.": ["Europe", "ba", 1, "Bosnia and Herzegovina"],
  "Botswana": ["Africa", "bw", 1, "Botswana"],
  "Br. Indian Ocean Ter.": ["Africa", "io", 0, "British Indian Ocean Territory"],
  "Brazil": ["South America", "br", 1, "Brazil"],
  "British Virgin Is.": ["North America", "vg", 0, "British Virgin Islands"],
  "Brunei": ["Asia", "bn", 1, "Brunei"],
  "Bulgaria": ["Europe", "bg", 1, "Bulgaria"],
  "Burkina Faso": ["Africa", "bf", 1, "Burkina Faso"],
  "Burundi": ["Africa", "bi", 1, "Burundi"],
  "Cabo Verde": ["Africa", "cv", 1, "Cape Verde"],
  "Cambodia": ["Asia", "kh", 1, "Cambodia"],
  "Cameroon": ["Africa", "cm", 1, "Cameroon"],
  "Canada": ["North America", "ca", 1, "Canada"],
  "Cayman Is.": ["North America", "ky", 0, "Cayman Islands"],
  "Central African Rep.": ["Africa", "cf", 1, "Central African Republic"],
  "Chad": ["Africa", "td", 1, "Chad"],
  "Chile": ["South America", "cl", 1, "Chile"],
  "China": ["Asia", "cn", 1, "China"],
  "Colombia": ["South America", "co", 1, "Colombia"],
  "Comoros": ["Africa", "km", 1, "Comoros"],
  "Congo": ["Africa", "cg", 1, "Republic of the Congo"],
  "Cook Is.": ["Oceania", "ck", 0, "Cook Islands"],
  "Costa Rica": ["North America", "cr", 1, "Costa Rica"],
  "Croatia": ["Europe", "hr", 1, "Croatia"],
  "Cuba": ["North America", "cu", 1, "Cuba"],
  "Cura\u00e7ao": ["North America", "cw", 0, "Cura\u00e7ao"],
  "Cyprus": ["Europe", "cy", 1, "Cyprus"],
  "Czechia": ["Europe", "cz", 1, "Czechia"],
  "C\u00f4te d'Ivoire": ["Africa", "ci", 1, "Ivory Coast"],
  "Dem. Rep. Congo": ["Africa", "cd", 1, "DR Congo"],
  "Denmark": ["Europe", "dk", 1, "Denmark"],
  "Djibouti": ["Africa", "dj", 1, "Djibouti"],
  "Dominica": ["North America", "dm", 1, "Dominica"],
  "Dominican Rep.": ["North America", "do", 1, "Dominican Republic"],
  "Ecuador": ["South America", "ec", 1, "Ecuador"],
  "Egypt": ["Africa", "eg", 1, "Egypt"],
  "El Salvador": ["North America", "sv", 1, "El Salvador"],
  "Eq. Guinea": ["Africa", "gq", 1, "Equatorial Guinea"],
  "Eritrea": ["Africa", "er", 1, "Eritrea"],
  "Estonia": ["Europe", "ee", 1, "Estonia"],
  "Ethiopia": ["Africa", "et", 1, "Ethiopia"],
  "Faeroe Is.": ["Europe", "fo", 0, "Faroe Islands"],
  "Falkland Is.": ["South America", "fk", 0, "Falkland Islands"],
  "Fiji": ["Oceania", "fj", 1, "Fiji"],
  "Finland": ["Europe", "fi", 1, "Finland"],
  "Fr. Polynesia": ["Oceania", "pf", 0, "French Polynesia"],
  "Fr. S. Antarctic Lands": ["Antarctica", "tf", 0, "French Southern and Antarctic Lands"],
  "France": ["Europe", "fr", 1, "France"],
  "Gabon": ["Africa", "ga", 1, "Gabon"],
  "Gambia": ["Africa", "gm", 1, "Gambia"],
  "Georgia": ["Asia", "ge", 1, "Georgia"],
  "Germany": ["Europe", "de", 1, "Germany"],
  "Ghana": ["Africa", "gh", 1, "Ghana"],
  "Greece": ["Europe", "gr", 1, "Greece"],
  "Greenland": ["North America", "gl", 0, "Greenland"],
  "Grenada": ["North America", "gd", 1, "Grenada"],
  "Guam": ["Oceania", "gu", 0, "Guam"],
  "Guatemala": ["North America", "gt", 1, "Guatemala"],
  "Guernsey": ["Europe", "gg", 0, "Guernsey"],
  "Guinea": ["Africa", "gn", 1, "Guinea"],
  "Guinea-Bissau": ["Africa", "gw", 1, "Guinea-Bissau"],
  "Guyana": ["South America", "gy", 1, "Guyana"],
  "Haiti": ["North America", "ht", 1, "Haiti"],
  "Heard I. and McDonald Is.": ["Antarctica", "hm", 0, "Heard Island and McDonald Islands"],
  "Honduras": ["North America", "hn", 1, "Honduras"],
  "Hong Kong": ["Asia", "hk", 0, "Hong Kong"],
  "Hungary": ["Europe", "hu", 1, "Hungary"],
  "Iceland": ["Europe", "is", 1, "Iceland"],
  "India": ["Asia", "in", 1, "India"],
  "Indian Ocean Ter.": ["Oceania", "", 0, "Indian Ocean Territories"],
  "Indonesia": ["Asia", "id", 1, "Indonesia"],
  "Iran": ["Asia", "ir", 1, "Iran"],
  "Iraq": ["Asia", "iq", 1, "Iraq"],
  "Ireland": ["Europe", "ie", 1, "Ireland"],
  "Isle of Man": ["Europe", "im", 0, "Isle of Man"],
  "Israel": ["Asia", "il", 1, "Israel"],
  "Italy": ["Europe", "it", 1, "Italy"],
  "Jamaica": ["North America", "jm", 1, "Jamaica"],
  "Japan": ["Asia", "jp", 1, "Japan"],
  "Jersey": ["Europe", "je", 0, "Jersey"],
  "Jordan": ["Asia", "jo", 1, "Jordan"],
  "Kazakhstan": ["Asia", "kz", 1, "Kazakhstan"],
  "Kenya": ["Africa", "ke", 1, "Kenya"],
  "Kiribati": ["Oceania", "ki", 1, "Kiribati"],
  "Kosovo": ["Europe", "xk", 1, "Kosovo"],
  "Kuwait": ["Asia", "kw", 1, "Kuwait"],
  "Kyrgyzstan": ["Asia", "kg", 1, "Kyrgyzstan"],
  "Laos": ["Asia", "la", 1, "Laos"],
  "Latvia": ["Europe", "lv", 1, "Latvia"],
  "Lebanon": ["Asia", "lb", 1, "Lebanon"],
  "Lesotho": ["Africa", "ls", 1, "Lesotho"],
  "Liberia": ["Africa", "lr", 1, "Liberia"],
  "Libya": ["Africa", "ly", 1, "Libya"],
  "Liechtenstein": ["Europe", "li", 1, "Liechtenstein"],
  "Lithuania": ["Europe", "lt", 1, "Lithuania"],
  "Luxembourg": ["Europe", "lu", 1, "Luxembourg"],
  "Macao": ["Asia", "mo", 0, "Macau"],
  "Macedonia": ["Europe", "mk", 1, "North Macedonia"],
  "Madagascar": ["Africa", "mg", 1, "Madagascar"],
  "Malawi": ["Africa", "mw", 1, "Malawi"],
  "Malaysia": ["Asia", "my", 1, "Malaysia"],
  "Maldives": ["Asia", "mv", 1, "Maldives"],
  "Mali": ["Africa", "ml", 1, "Mali"],
  "Malta": ["Europe", "mt", 1, "Malta"],
  "Marshall Is.": ["Oceania", "mh", 1, "Marshall Islands"],
  "Mauritania": ["Africa", "mr", 1, "Mauritania"],
  "Mauritius": ["Africa", "mu", 1, "Mauritius"],
  "Mexico": ["North America", "mx", 1, "Mexico"],
  "Micronesia": ["Oceania", "fm", 1, "Micronesia"],
  "Moldova": ["Europe", "md", 1, "Moldova"],
  "Monaco": ["Europe", "mc", 1, "Monaco"],
  "Mongolia": ["Asia", "mn", 1, "Mongolia"],
  "Montenegro": ["Europe", "me", 1, "Montenegro"],
  "Montserrat": ["North America", "ms", 0, "Montserrat"],
  "Morocco": ["Africa", "ma", 1, "Morocco"],
  "Mozambique": ["Africa", "mz", 1, "Mozambique"],
  "Myanmar": ["Asia", "mm", 1, "Myanmar"],
  "N. Cyprus": ["Asia", "", 0, "Northern Cyprus"],
  "N. Mariana Is.": ["Oceania", "mp", 0, "Northern Mariana Islands"],
  "Namibia": ["Africa", "na", 1, "Namibia"],
  "Nauru": ["Oceania", "nr", 1, "Nauru"],
  "Nepal": ["Asia", "np", 1, "Nepal"],
  "Netherlands": ["Europe", "nl", 1, "Netherlands"],
  "New Caledonia": ["Oceania", "nc", 0, "New Caledonia"],
  "New Zealand": ["Oceania", "nz", 1, "New Zealand"],
  "Nicaragua": ["North America", "ni", 1, "Nicaragua"],
  "Niger": ["Africa", "ne", 1, "Niger"],
  "Nigeria": ["Africa", "ng", 1, "Nigeria"],
  "Niue": ["Oceania", "nu", 0, "Niue"],
  "Norfolk Island": ["Oceania", "nf", 0, "Norfolk Island"],
  "North Korea": ["Asia", "kp", 1, "North Korea"],
  "Norway": ["Europe", "no", 1, "Norway"],
  "Oman": ["Asia", "om", 1, "Oman"],
  "Pakistan": ["Asia", "pk", 1, "Pakistan"],
  "Palau": ["Oceania", "pw", 1, "Palau"],
  "Palestine": ["Asia", "ps", 1, "Palestine"],
  "Panama": ["North America", "pa", 1, "Panama"],
  "Papua New Guinea": ["Oceania", "pg", 1, "Papua New Guinea"],
  "Paraguay": ["South America", "py", 1, "Paraguay"],
  "Peru": ["South America", "pe", 1, "Peru"],
  "Philippines": ["Asia", "ph", 1, "Philippines"],
  "Pitcairn Is.": ["Oceania", "pn", 0, "Pitcairn Islands"],
  "Poland": ["Europe", "pl", 1, "Poland"],
  "Portugal": ["Europe", "pt", 1, "Portugal"],
  "Puerto Rico": ["North America", "pr", 0, "Puerto Rico"],
  "Qatar": ["Asia", "qa", 1, "Qatar"],
  "Romania": ["Europe", "ro", 1, "Romania"],
  "Russia": ["Europe", "ru", 1, "Russia"],
  "Rwanda": ["Africa", "rw", 1, "Rwanda"],
  "S. Geo. and the Is.": ["Antarctica", "gs", 0, "South Georgia"],
  "S. Sudan": ["Africa", "ss", 1, "South Sudan"],
  "Saint Helena": ["Africa", "sh", 0, "Saint Helena, Ascension and Tristan da Cunha"],
  "Saint Lucia": ["North America", "lc", 1, "Saint Lucia"],
  "Samoa": ["Oceania", "ws", 1, "Samoa"],
  "San Marino": ["Europe", "sm", 1, "San Marino"],
  "Saudi Arabia": ["Asia", "sa", 1, "Saudi Arabia"],
  "Senegal": ["Africa", "sn", 1, "Senegal"],
  "Serbia": ["Europe", "rs", 1, "Serbia"],
  "Seychelles": ["Africa", "sc", 1, "Seychelles"],
  "Siachen Glacier": ["Asia", "", 0, "Siachen Glacier"],
  "Sierra Leone": ["Africa", "sl", 1, "Sierra Leone"],
  "Singapore": ["Asia", "sg", 1, "Singapore"],
  "Sint Maarten": ["North America", "sx", 0, "Sint Maarten"],
  "Slovakia": ["Europe", "sk", 1, "Slovakia"],
  "Slovenia": ["Europe", "si", 1, "Slovenia"],
  "Solomon Is.": ["Oceania", "sb", 1, "Solomon Islands"],
  "Somalia": ["Africa", "so", 1, "Somalia"],
  "Somaliland": ["Africa", "", 0, "Somaliland"],
  "South Africa": ["Africa", "za", 1, "South Africa"],
  "South Korea": ["Asia", "kr", 1, "South Korea"],
  "Spain": ["Europe", "es", 1, "Spain"],
  "Sri Lanka": ["Asia", "lk", 1, "Sri Lanka"],
  "St-Barth\u00e9lemy": ["North America", "bl", 0, "Saint Barth\u00e9lemy"],
  "St-Martin": ["North America", "mf", 0, "Saint Martin"],
  "St. Kitts and Nevis": ["North America", "kn", 1, "Saint Kitts and Nevis"],
  "St. Pierre and Miquelon": ["North America", "pm", 0, "Saint Pierre and Miquelon"],
  "St. Vin. and Gren.": ["North America", "vc", 1, "Saint Vincent and the Grenadines"],
  "Sudan": ["Africa", "sd", 1, "Sudan"],
  "Suriname": ["South America", "sr", 1, "Suriname"],
  "Sweden": ["Europe", "se", 1, "Sweden"],
  "Switzerland": ["Europe", "ch", 1, "Switzerland"],
  "Syria": ["Asia", "sy", 1, "Syria"],
  "S\u00e3o Tom\u00e9 and Principe": ["Africa", "st", 1, "S\u00e3o Tom\u00e9 and Pr\u00edncipe"],
  "Taiwan": ["Asia", "tw", 1, "Taiwan"],
  "Tajikistan": ["Asia", "tj", 1, "Tajikistan"],
  "Tanzania": ["Africa", "tz", 1, "Tanzania"],
  "Thailand": ["Asia", "th", 1, "Thailand"],
  "Timor-Leste": ["Asia", "tl", 1, "Timor-Leste"],
  "Togo": ["Africa", "tg", 1, "Togo"],
  "Tonga": ["Oceania", "to", 1, "Tonga"],
  "Trinidad and Tobago": ["North America", "tt", 1, "Trinidad and Tobago"],
  "Tunisia": ["Africa", "tn", 1, "Tunisia"],
  "Turkey": ["Asia", "tr", 1, "Turkey"],
  "Turkmenistan": ["Asia", "tm", 1, "Turkmenistan"],
  "Turks and Caicos Is.": ["North America", "tc", 0, "Turks and Caicos Islands"],
  "U.S. Virgin Is.": ["North America", "vi", 0, "United States Virgin Islands"],
  "Uganda": ["Africa", "ug", 1, "Uganda"],
  "Ukraine": ["Europe", "ua", 1, "Ukraine"],
  "United Arab Emirates": ["Asia", "ae", 1, "United Arab Emirates"],
  "United Kingdom": ["Europe", "gb", 1, "United Kingdom"],
  "United States of America": ["North America", "us", 1, "United States"],
  "Uruguay": ["South America", "uy", 1, "Uruguay"],
  "Uzbekistan": ["Asia", "uz", 1, "Uzbekistan"],
  "Vanuatu": ["Oceania", "vu", 1, "Vanuatu"],
  "Vatican": ["Europe", "va", 1, "Vatican City"],
  "Venezuela": ["South America", "ve", 1, "Venezuela"],
  "Vietnam": ["Asia", "vn", 1, "Vietnam"],
  "W. Sahara": ["Africa", "eh", 0, "Western Sahara"],
  "Wallis and Futuna Is.": ["Oceania", "wf", 0, "Wallis and Futuna"],
  "Yemen": ["Asia", "ye", 1, "Yemen"],
  "Zambia": ["Africa", "zm", 1, "Zambia"],
  "Zimbabwe": ["Africa", "zw", 1, "Zimbabwe"],
  "eSwatini": ["Africa", "sz", 1, "Eswatini"],
  "\u00c5land": ["Europe", "ax", 0, "\u00c5land Islands"],
};

window.displayName = (name) => {
  const m = window.COUNTRY_META[name];
  return m ? m[3] : name;
};
