// All 63 US National Parks. `wiki` is the Wikipedia article title used to
// fetch a photo (free, no API key). Coordinates are approximate park centers.

window.PARKS = [
  { name: "Acadia", state: "Maine", lat: 44.35, lon: -68.21, wiki: "Acadia National Park" },
  { name: "American Samoa", state: "American Samoa", lat: -14.25, lon: -170.68, wiki: "National Park of American Samoa" },
  { name: "Arches", state: "Utah", lat: 38.68, lon: -109.57, wiki: "Arches National Park" },
  { name: "Badlands", state: "South Dakota", lat: 43.75, lon: -102.50, wiki: "Badlands National Park" },
  { name: "Big Bend", state: "Texas", lat: 29.25, lon: -103.25, wiki: "Big Bend National Park" },
  { name: "Biscayne", state: "Florida", lat: 25.65, lon: -80.08, wiki: "Biscayne National Park" },
  { name: "Black Canyon of the Gunnison", state: "Colorado", lat: 38.57, lon: -107.72, wiki: "Black Canyon of the Gunnison National Park" },
  { name: "Bryce Canyon", state: "Utah", lat: 37.57, lon: -112.18, wiki: "Bryce Canyon National Park" },
  { name: "Canyonlands", state: "Utah", lat: 38.20, lon: -109.93, wiki: "Canyonlands National Park" },
  { name: "Capitol Reef", state: "Utah", lat: 38.20, lon: -111.17, wiki: "Capitol Reef National Park" },
  { name: "Carlsbad Caverns", state: "New Mexico", lat: 32.17, lon: -104.44, wiki: "Carlsbad Caverns National Park" },
  { name: "Channel Islands", state: "California", lat: 34.01, lon: -119.42, wiki: "Channel Islands National Park" },
  { name: "Congaree", state: "South Carolina", lat: 33.78, lon: -80.78, wiki: "Congaree National Park" },
  { name: "Crater Lake", state: "Oregon", lat: 42.94, lon: -122.10, wiki: "Crater Lake National Park" },
  { name: "Cuyahoga Valley", state: "Ohio", lat: 41.24, lon: -81.55, wiki: "Cuyahoga Valley National Park" },
  { name: "Death Valley", state: "California", lat: 36.24, lon: -116.82, wiki: "Death Valley National Park" },
  { name: "Denali", state: "Alaska", lat: 63.33, lon: -150.50, wiki: "Denali National Park and Preserve" },
  { name: "Dry Tortugas", state: "Florida", lat: 24.63, lon: -82.87, wiki: "Dry Tortugas National Park" },
  { name: "Everglades", state: "Florida", lat: 25.32, lon: -80.93, wiki: "Everglades National Park" },
  { name: "Gates of the Arctic", state: "Alaska", lat: 67.78, lon: -153.30, wiki: "Gates of the Arctic National Park and Preserve" },
  { name: "Gateway Arch", state: "Missouri", lat: 38.63, lon: -90.19, wiki: "Gateway Arch National Park" },
  { name: "Glacier", state: "Montana", lat: 48.80, lon: -114.00, wiki: "Glacier National Park (U.S.)" },
  { name: "Glacier Bay", state: "Alaska", lat: 58.50, lon: -137.00, wiki: "Glacier Bay National Park and Preserve" },
  { name: "Grand Canyon", state: "Arizona", lat: 36.06, lon: -112.14, wiki: "Grand Canyon National Park" },
  { name: "Grand Teton", state: "Wyoming", lat: 43.73, lon: -110.80, wiki: "Grand Teton National Park" },
  { name: "Great Basin", state: "Nevada", lat: 38.98, lon: -114.30, wiki: "Great Basin National Park" },
  { name: "Great Sand Dunes", state: "Colorado", lat: 37.73, lon: -105.51, wiki: "Great Sand Dunes National Park and Preserve" },
  { name: "Great Smoky Mountains", state: "Tennessee / North Carolina", lat: 35.68, lon: -83.53, wiki: "Great Smoky Mountains National Park" },
  { name: "Guadalupe Mountains", state: "Texas", lat: 31.92, lon: -104.87, wiki: "Guadalupe Mountains National Park" },
  { name: "Haleakalā", state: "Hawaii", lat: 20.72, lon: -156.17, wiki: "Haleakalā National Park" },
  { name: "Hawaiʻi Volcanoes", state: "Hawaii", lat: 19.38, lon: -155.20, wiki: "Hawaiʻi Volcanoes National Park" },
  { name: "Hot Springs", state: "Arkansas", lat: 34.51, lon: -93.05, wiki: "Hot Springs National Park" },
  { name: "Indiana Dunes", state: "Indiana", lat: 41.65, lon: -87.05, wiki: "Indiana Dunes National Park" },
  { name: "Isle Royale", state: "Michigan", lat: 48.10, lon: -88.55, wiki: "Isle Royale National Park" },
  { name: "Joshua Tree", state: "California", lat: 33.79, lon: -115.90, wiki: "Joshua Tree National Park" },
  { name: "Katmai", state: "Alaska", lat: 58.50, lon: -155.00, wiki: "Katmai National Park and Preserve" },
  { name: "Kenai Fjords", state: "Alaska", lat: 59.92, lon: -149.65, wiki: "Kenai Fjords National Park" },
  { name: "Kings Canyon", state: "California", lat: 36.80, lon: -118.55, wiki: "Kings Canyon National Park" },
  { name: "Kobuk Valley", state: "Alaska", lat: 67.55, lon: -159.28, wiki: "Kobuk Valley National Park" },
  { name: "Lake Clark", state: "Alaska", lat: 60.97, lon: -153.42, wiki: "Lake Clark National Park and Preserve" },
  { name: "Lassen Volcanic", state: "California", lat: 40.49, lon: -121.51, wiki: "Lassen Volcanic National Park" },
  { name: "Mammoth Cave", state: "Kentucky", lat: 37.18, lon: -86.10, wiki: "Mammoth Cave National Park" },
  { name: "Mesa Verde", state: "Colorado", lat: 37.18, lon: -108.49, wiki: "Mesa Verde National Park" },
  { name: "Mount Rainier", state: "Washington", lat: 46.85, lon: -121.75, wiki: "Mount Rainier National Park" },
  { name: "New River Gorge", state: "West Virginia", lat: 37.93, lon: -81.07, wiki: "New River Gorge National Park and Preserve" },
  { name: "North Cascades", state: "Washington", lat: 48.70, lon: -121.20, wiki: "North Cascades National Park" },
  { name: "Olympic", state: "Washington", lat: 47.97, lon: -123.50, wiki: "Olympic National Park" },
  { name: "Petrified Forest", state: "Arizona", lat: 35.07, lon: -109.78, wiki: "Petrified Forest National Park" },
  { name: "Pinnacles", state: "California", lat: 36.48, lon: -121.16, wiki: "Pinnacles National Park" },
  { name: "Redwood", state: "California", lat: 41.30, lon: -124.00, wiki: "Redwood National and State Parks" },
  { name: "Rocky Mountain", state: "Colorado", lat: 40.40, lon: -105.58, wiki: "Rocky Mountain National Park" },
  { name: "Saguaro", state: "Arizona", lat: 32.25, lon: -110.50, wiki: "Saguaro National Park" },
  { name: "Sequoia", state: "California", lat: 36.43, lon: -118.68, wiki: "Sequoia National Park" },
  { name: "Shenandoah", state: "Virginia", lat: 38.53, lon: -78.35, wiki: "Shenandoah National Park" },
  { name: "Theodore Roosevelt", state: "North Dakota", lat: 46.97, lon: -103.45, wiki: "Theodore Roosevelt National Park" },
  { name: "Virgin Islands", state: "US Virgin Islands", lat: 18.33, lon: -64.73, wiki: "Virgin Islands National Park" },
  { name: "Voyageurs", state: "Minnesota", lat: 48.50, lon: -92.88, wiki: "Voyageurs National Park" },
  { name: "White Sands", state: "New Mexico", lat: 32.78, lon: -106.17, wiki: "White Sands National Park" },
  { name: "Wind Cave", state: "South Dakota", lat: 43.57, lon: -103.48, wiki: "Wind Cave National Park" },
  { name: "Wrangell–St. Elias", state: "Alaska", lat: 61.00, lon: -142.00, wiki: "Wrangell–St. Elias National Park and Preserve" },
  { name: "Yellowstone", state: "Wyoming / Montana / Idaho", lat: 44.60, lon: -110.50, wiki: "Yellowstone National Park" },
  { name: "Yosemite", state: "California", lat: 37.83, lon: -119.50, wiki: "Yosemite National Park" },
  { name: "Zion", state: "Utah", lat: 37.30, lon: -113.05, wiki: "Zion National Park" },
];
